### ISSUE TITLE
Non-ASCII characters are replaced by �

### ISSUE THREAD

**Issue by JbCourtois** [jsoncomma/sublime-jsoncomma#21]
**Input**: `{"test": "Démonstration",}`

**Expected Output:** `{"test": "Démonstration"}`

**Actual Output:** `{"test": "D�monstration"}`

**Comment by simoncozens** [comment]
Characters outside of Latin-1 get an even rougher time:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "/Users/simon/Library/Application Support/Sublime Text 3/Installed Packages/JSONComma.sublime-package/jsoncomma.py", line 92, in run
  File "/Users/simon/Library/Application Support/Sublime Text 3/Installed Packages/JSONComma.sublime-package/server.py", line 190, in fix
  File "/Users/simon/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/simon/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/simon/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/simon/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "/Users/simon/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/adapters.py", line 439, in send
    timeout=timeout
  File "/Users/simon/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/simon/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1102, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 179-181: ordinal not in range(256)
```

**Comment by ad-si** [comment]
JSONComma is really helpful, but unfortunately I had to remove it because of this bug ☹️
